name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]  # You can add more versions if needed

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies in the 'api' folder
      - name: Install dependencies
        run: npm install --prefix api

      # Run linter (ESLint)
      #- name: Run linter
      #  run: npm run lint --prefix api

      # Run tests (Jest, if set up)
      #- name: Run tests
      #  run: npm test --prefix api

      # Start the server to ensure it starts without issues, directly referencing the 'api' folder
      - name: Start the server
        run: node api/app.js &
        env:
          PORT: 3002

      # Health check (optional, ensure the app is accessible)
      #- name: Check if server is running
      #  run: |
      #    sleep 5
      #    curl -v --fail http://localhost:3002 || exit 1
